Repository Natalina-Yarosh/FE66-onl-axit, pull requests merged in 2024-11, with the labels that each got.

#23 add hw4
  index.html
  style/style.css
  styles.css
Labels: merge

#20 feat: change class name
  index.html
  style/style-index.css
Labels: merge

#5 merge homework4 in my main
  stranichka2/index.html
  stranichka2/style/style.css
  style/style.css
Labels: merge

#28 Add reut-hw in my main branch reut
  image/image1.png
  image/image2.png
  image/image3.png
  index.html
  style/style.css
Labels: merge

#34 Chodenkova hw-4 dop
  img 1.png
  img 2.png
  img 3.png
  index.html
  style/style.css
Labels: merge

#30 sinitsa_hw
  img/Cooper.jpg
  img/Davis.jpg
  img/Jaydon.jpg
  index.html
  styles.css
Labels: ready for review

#31 feat: add reviews block
  img/cooper.png
  img/davis.png
  img/jaydon.png
  index.html
  style/style.css
Labels: ready for review

#29 Dasha hw additional
  index.html
  style/style-index.css
Labels: merge

#39 init(hw_5): tabs
  images/Ellipse7.png
  images/Ellipse8.png
  images/Ellipse9.png
  images/tabsimg1.jpg
  index.html
  style/style.css
Labels: merge

#37 merge hw into borisevich
  index.html
  photo/persone1.png
  photo/persone2.png
  photo/persone3.png
  style/style.css
Labels: merge

#32 feat: Bobinin hw4 fixes2
  .idea/modules.xml
  .idea/vcs.xml
  index.html
  style/style.css
Labels: merge

#44 Add tabs block in homework
  image/Rectangle111.jpg
  index.html
  style/style.css
Labels: merge

#38 azarkevich hw additional
  img/img1.png
  img/img2.png
  img/img3.png
  index.html
  style/style.css
Labels: merge

#54 feat: add tabs block
  img/statue.jpg
  index.html
  style/style.css
Labels: merge

#45 feat: add block Tabs
  index.html
  media/customers-1.png
  media/customers-2.png
  media/customers-3.png
  media/tabs-img.jpg
  style/style.css
Labels: merge

#59 i did my homework_6
  index.html
  style.css
Labels: merge

#52 azarkevich_hw5
  img/Rectangle 111.png
  img/img1.png
  img/img2.png
  img/img3.png
  index.html
  style/style.css
Labels: merge

#48 sinitsa_hw_5
  img/tabs_photo.jpg
  index.html
  styles.css
Labels: merge

#60 init(hw_6): social media
  index.html
  style/style.css
Labels: merge

#57 Danilevich hw-4
  .DS_Store
  index.html
  media/Cooper Dorwart.jpg
  media/Davis Rhiel Madsen.jpg
  media/Jaydon Rosser.jpg
  media/Tabs1.png
  style/style.css
Labels: merge

#51 merge borisevich-hw_5 into borisevich
  index.html
  photo/Statue.jpg
  style/style.css
Labels: merge

#49 feat(hw_5): add 2 new blocks
  images/photo1.png
  images/photo2.png
  images/photo3.png
  images/photo4.png
  index.html
  style/style.css
Labels: merge

#42 hw5-Dasha
  index.html
  style/style-index.css
Labels: ready for review

#61 Add Social Media block
  image/banner.png
  index.html
  style/style.css
Labels: merge

#71 sinitsa_hw_6
  index.html
  style/style.css
  styles.css
Labels: merge

#56 Savenok hw 4
  Rectangle 111.png
  index.html
  style/style.css
Labels: merge

#35 merge Arina1122_hw-5
  css/style.css
  index.html
  media/NY.jpg
  media/customer_1.png
  media/customer_2.png
  media/customer_3.png
Labels: merge

#67 Axit 4 hw
  index.html
  photos/axit-3_photo.png
  style/style.css
Labels: merge

#63 add social block
  index.html
  style/style.css
Labels: merge

#72 Dasha_hw-7
  index.html
  media/1.jpg
  media/2.jpg
  style/style-index.css
Labels: merge

#73 init(hw_7):add 4 new bloks
  images/design_background.jpg
  images/main_background.jpg
  index.html
  style/style.css
Labels: merge

#77 hw7
  img/city.jpg
  img/street.png
  index.html
  style/style.css
Labels: merge

#88 Axit 5 2 new blocks
  index.html
  photos/night-city_axit-5.jpg
  style/style.css
Labels: merge

#84 azarkevich_hw7
  additional/index.html
  additional/style/style.css
  img/bg.png
  img/image.png
  img/imagecitynight.png
  img/img1.png
  img/img2.png
  img/img3.png
  index.html
  style/style.css
Labels: merge

#74 feat(hw_7): add new blocks
  images/photo5.png
  images/photo6.png
  index.html
  style/style.css
Labels: need to fix

#92 Dasha Finish Axit
  index.html
  style/style-index.css
Labels: done

#58 Finish Axit v5
  images/axbg.jpg
  images/bg.jpg
  images/img1.png
  images/img2.png
  images/img3.png
  images/state.jpg
  index.html
  style/style.css
Labels: done

#98 Finish Axit
  image/design.jpg
  index.html
  style/style.css
Labels: done

#83 Finish Axit (sinitsa)
  img/2.png
  img/bannner.png
  index.html
  style/style.css
Labels: done

#89 Finish Axit
  index.html
  media/banner.png
  media/stylish.jpg
  style/style.css
Labels: done

#90 vrublevski Finish Axit
  index.html
  style/style.css
Labels: done

#93 Finish Axit
  index.html
  photo/Back1.png
  photo/Back2.jpg
  style/style.css
Labels: done
